[package]
name = "router"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tonic = "0.14.2"
prost = "0.14.1"

[build-dependencies]
tonic-prost-build = "0.14.2"